---
openapi: 3.0.0
info:
  title: Users API
  description: An API for managing users
  version: 1.0.0
paths:
  /users:
    get:
      summary: All users
      operationId: listUsers
      description: List all users
      responses:
        200:
          description: Returns the list of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Creates a user
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: A user was created succesfully
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    User:
      required:
      - firstName
      properties:
        firstName:
          type: string
        lastName:
          type: string
