openapi: 3.0.0
info:
  title: Test API
  description: My test API
  version: 1.0.0
paths:
  /users:
    get:
      summary: List all users
      operationId: listUsers
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 100
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserWithId'
    post:
      summary: Add a new user
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithId'
components:
  schemas:
    UserWithId:
      allOf:
        - $ref: '#/components/schemas/User'
        - properties:
          id:
            type: string
          required:
            - id
    User:
      required:
      - firstName
      properties:
        firstName:
          type: string
        lastName:
          type: string

